# Muhammad Sadqain
# PIAIC122829

In [1]:
import numpy as np

# The Numpy ndarray: A Multidimensional Array Object

In [2]:
#Function 1
# ndarray is multi dimensional container for homogenous data
data = np.array([[118, 246, 8856], [39, 879, 9854]] )
data

array([[ 118,  246, 8856],
       [  39,  879, 9854]])

In [4]:
#Function 2
data * 5

array([[  590,  1230, 44280],
       [  195,  4395, 49270]])

In [5]:
data.shape

(2, 3)

In [7]:
# ndarray data type
data.dtype

dtype('int32')

# Creating ndarrays

In [8]:
dataSadqain = [1, 16, 42, 34,25]

# list to ndarray
array1 = np.array(dataSadqain)

array1

array([ 1, 16, 42, 34, 25])

In [12]:
# nested sequence will be converted into multi dimensional array
dataSadqainpro = [[10, 20 , 30, 50],[50, 60, 70, 80]]

array2 = np.array(dataSadqainpro)

array2

array([[10, 20, 30, 50],
       [50, 60, 70, 80]])

In [13]:
print( "array2 dim :" ,array2.ndim) 
print("array1 dim :",array1.ndim)

array2 dim : 2
array1 dim : 1


In [14]:
print( "array2 shape :",array2.shape) 
print("array1 shape :",array1.shape)

array2 shape : (2, 4)
array1 shape : (5,)


In [15]:
print( "array2 datatype :" ,array2.dtype) 
print("array1 datatype :",array1.dtype)

array2 datatype : int32
array1 datatype : int32


In [20]:
# single dim zeros array
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
# multi dim zeros array
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# single dim ones array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
# multi dim ones array
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
# np.empty creates unintialized array
np.empty((2,2))

array([[5.e-324, 5.e-324],
       [0.e+000, 0.e+000]])

In [28]:
# our favorite arange
s= np.arange(5)
s

array([0, 1, 2, 3, 4])

In [29]:
# takes another array and produce ones like array of that array size
np.ones_like(s)

array([1, 1, 1, 1, 1])

In [33]:
np.zeros_like(s)

array([0, 0, 0, 0, 0])

In [34]:
# np.identity is same as np.eye which produces identity matirix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Data Types of ndarrays

In [36]:
array3 = np.array([1, 2, 3], dtype=np.float64)
array4 = np.array([1, 2, 4], dtype= np.int32)

In [37]:

array3.dtype,array4.dtype

(dtype('float64'), dtype('int32'))

In [38]:
# you can also use another array's dtype attribute
int_array = np.arange(10)
print("int_array dtype: ",int_array.dtype)

float_array = np.array([1, 3, 4, 5], dtype= float)
print("float array dtype: ",float_array.dtype)

int_to_float = int_array.astype(float_array.dtype)
print("int_to_float dtype: ",int_to_float.dtype)

int_array dtype:  int32
float array dtype:  float64
int_to_float dtype:  float64


# Operations between Array and Scalars

In [40]:
array2 = np.array([[12, 21, 34],[43, 53, 65]], dtype=float)
array2

array([[12., 21., 34.],
       [43., 53., 65.]])

In [41]:
# arithematic operations
1/ array2

array([[0.08333333, 0.04761905, 0.02941176],
       [0.02325581, 0.01886792, 0.01538462]])

# Basic Indexing and Slicing

In [42]:
# one dimesional array

arr = np.arange(14)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [43]:
# assigning scalar value to a slice
arr[2:7] = 12
arr

array([ 0,  1, 12, 12, 12, 12, 12,  7,  8,  9, 10, 11, 12, 13])

In [44]:
arr_slice = arr[3:6]
arr_slice[1] = 7868

In [50]:
arry2d = np.array([[11, 22, 33],[44, 55, 66],[77, 88, 99]])
arry2d

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [51]:
arry2d[2]

array([77, 88, 99])

In [52]:
# to access single element of multi dim arry
print(arry2d[0][2])
#or
print(arry2d[0, 2])

33
33


# Fancy Indexing
### Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had a 8 × 4 array:

In [57]:
arr = np.empty((8, 4))
for i in range(5):
    arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [58]:
# to select out a subset of the rows in a particular order, we can simple pass a list

arr[[4, 3, 0, 6]]  #4th row, 3rd row, 0th row, 6th row

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [59]:
# using negative indices select row from the end

arr[[-3, -5, 7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

# Transposing Arrays and Swapping Axes

In [61]:
array = np.arange(25).reshape((5, 5))
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
array.T

array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

In [63]:
# matrix computation

arr = np.random.randn(6, 3)
arr

array([[-0.90579779,  1.38716872, -1.79838162],
       [ 1.68910113, -0.97810297,  0.05382306],
       [ 1.95435587,  0.19073087,  1.33328079],
       [-0.27552257,  1.41646776,  0.66849996],
       [-0.81243527,  1.1227327 ,  2.51031406],
       [ 0.35330388, -1.48193915, -0.0491568 ]])

# Universal Functions: Fast Element-wise Array Functions

In [64]:
s = np.arange(14)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [65]:
# unary ufunc(because it take one value)
np.sqrt(s)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128])

In [66]:
# unary ufunc(it taks one value)
np.exp(s)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05])

In [67]:
# binary ufunc
x = np.random.randn(8)
y = np.random.randn(8)

np.maximum(x, y)

array([-0.22129659,  0.76960893,  0.68084734,  1.20795232,  0.38112935,
        0.79094896,  0.9387798 ,  0.76597581])

In [70]:
np.log(14), np.log10(12), np.log2(15), np.log1p(9)

(2.6390573296152584, 1.0791812460476249, 3.9068905956085187, 2.302585092994046)

# Data Processing Using Arrays

In [71]:
pointsadqain = np.arange(-5, 5, 0.01)  # 1k equally spaced points

In [73]:
# the meshgrid take two 1D arrays and produces two 2D arrays
xs, ys = np.meshgrid(pointsadqain, pointsadqain)

In [74]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [75]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [76]:
import matplotlib.pyplot as plt

In [78]:
sid = np.sqrt(xs **2 + ys ** 2)
sid

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

# Methods for Boolean Arrays

In [82]:
arraysadqain = np.random.randn(50)
(arraysadqain > 0).sum()   
# number of positive values

24

In [83]:
# any() check if whether one or more values in any array is True 
bools = arraysadqain.any()
bools

True

In [85]:
# all() check if every value is True
arraysadqain.all()

True

# Random Number Generation

In [87]:
# rando number form normal ditribution
import numpy as np
normal = np.random.normal(size=(5, 5))
normal

array([[-2.43071343, -1.88182388,  0.56570376, -0.5616279 , -0.10586489],
       [-2.22165677, -1.26681525, -1.96079446,  0.93548621,  0.94838294],
       [-2.39715138,  1.05093782,  1.59682245,  0.91558005, -0.15718265],
       [-0.95692057, -2.56798729, -0.69419431,  2.54781404, -0.03635767],
       [-0.28046387,  0.93781582, -0.91727596, -0.45487463,  1.06438   ]])

In [88]:
# seed -- seed the random number generator
np.random.seed(4)
np.random.randn(2, 3)

array([[ 0.05056171,  0.49995133, -0.99590893],
       [ 0.69359851, -0.41830152, -1.58457724]])

# Sorting

In [89]:
arr =np.random.randn(8)
arr

array([-0.64770677,  0.59857517,  0.33225003, -1.14747663,  0.61866969,
       -0.08798693,  0.4250724 ,  0.33225315])

In [90]:
# sorting in place
arr.sort()

In [91]:
arr = np.array([[5, 3, 3, 4],[4, 1, 2, 4]])

arr

array([[5, 3, 3, 4],
       [4, 1, 2, 4]])